export const mockTVStations = [
  { id: 1, name: "ABC News" },
  { id: 2, name: "BBC" },
  { id: 3, name: "ESPN" },
  { id: 4, name: "NBC" },
  { id: 5, name: "CBS" },
  { id: 6, name: "CNN" },
  { id: 7, name: "Fox News" },
  { id: 8, name: "MTV" },
  { id: 9, name: "Discovery Channel" },
  { id: 10, name: "National Geographic" },
];

export const mockEmails = [
  {
    id: 1,
    type: "to",
    email: "john.doe@example.com",
    option1: false,
    option2: false,
    option3: false,
    tvStation: "ABC News",
  },
  {
    id: 2,
    type: "cc",
    email: "jane.smith@example.com",
    option1: true,
    option2: false,
    option3: true,
    tvStation: "BBC",
  },
  {
    id: 3,
    type: "bcc",
    email: "mark.jones@example.com",
    option1: false,
    option2: true,
    option3: false,
    tvStation: "ESPN",
  },
  {
    id: 4,
    type: "to",
    email: "alice.wang@example.com",
    option1: true,
    option2: true,
    option3: false,
    tvStation: "NBC",
  },
  {
    id: 5,
    type: "cc",
    email: "mike.brown@example.com",
    option1: false,
    option2: true,
    option3: true,
    tvStation: "CBS",
  },
  {
    id: 6,
    type: "bcc",
    email: "lisa.white@example.com",
    option1: true,
    option2: false,
    option3: false,
    tvStation: "CNN",
  },
  {
    id: 7,
    type: "to",
    email: "peter.parker@example.com",
    option1: false,
    option2: false,
    option3: true,
    tvStation: "Fox News",
  },
  {
    id: 8,
    type: "cc",
    email: "bruce.wayne@example.com",
    option1: true,
    option2: true,
    option3: false,
    tvStation: "MTV",
  },
  {
    id: 9,
    type: "bcc",
    email: "diana.prince@example.com",
    option1: false,
    option2: true,
    option3: true,
    tvStation: "Discovery Channel",
  },
  {
    id: 10,
    type: "to",
    email: "clark.kent@example.com",
    option1: true,
    option2: false,
    option3: false,
    tvStation: "ABC News",
  },
  {
    id: 11,
    type: "to",
    email: "john.doe@anotherdomain.com",
    option1: true,
    option2: false,
    option3: true,
    tvStation: "ABC News",
  },
  {
    id: 12,
    type: "bcc",
    email: "jane.smith@differentdomain.com",
    option1: false,
    option2: true,
    option3: false,
    tvStation: "BBC",
  },
  {
    id: 13,
    type: "cc",
    email: "alice.wang@sample.com",
    option1: true,
    option2: false,
    option3: true,
    tvStation: "NBC",
  },
  {
    id: 14,
    type: "to",
    email: "john.doe@anotherdomain.com",
    option1: false,
    option2: true,
    option3: false,
    tvStation: "Fox News",
  },
  {
    id: 15,
    type: "bcc",
    email: "clark.kent@dailyplanet.com",
    option1: true,
    option2: true,
    option3: false,
    tvStation: "ABC News",
  },
  {
    id: 16,
    type: "to",
    email: "mike.brown@example.com",
    option1: true,
    option2: true,
    option3: false,
    tvStation: "CBS",
  },
  {
    id: 17,
    type: "cc",
    email: "diana.prince@example.com",
    option1: true,
    option2: false,
    option3: true,
    tvStation: "Discovery Channel",
  },
  {
    id: 18,
    type: "to",
    email: "lisa.white@example.com",
    option1: false,
    option2: true,
    option3: false,
    tvStation: "CNN",
  },
  {
    id: 19,
    type: "bcc",
    email: "bruce.wayne@wayneenterprises.com",
    option1: false,
    option2: false,
    option3: true,
    tvStation: "MTV",
  },
  {
    id: 20,
    type: "cc",
    email: "john.doe@customdomain.com",
    option1: true,
    option2: false,
    option3: false,
    tvStation: "ESPN",
  },
];
