export const mockProgramInfo = [
  {
    id: 1,
    name: "John Doe",
    age: 25,
    airStart: new Date(2021, 6, 15),
    airEnd: new Date(2021, 6, 20),
    status: "作成完了",
    fileName: "aaaaa.xlsx",
    uploadDate: new Date(),
    message: "あああああ",
    reason: "あああああ",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 36,
    airStart: new Date(2022, 3, 20),
    airEnd: new Date(2022, 4, 20),
    status: "確定",
    fileName: "bbbbb.xlsx",
    uploadDate: new Date(),
    message:
      "ああああああああああああああああああああああああああああああああああああああああ",
    reason: "あああああ",
  },
  {
    id: 3,
    name: "Bob Johnson",
    age: 28,
    airStart: new Date(2023, 1, 10),
    airEnd: new Date(2024, 1, 10),
    status: "差戻し",
    fileName: "ccccc.xlsx",
    uploadDate: new Date(),
    message: "あああああ",
    reason:
      "ああああああああああああああああああああああああああああああああああああああああ",
  },
];
