export const mockProgramInfo = [
  {
    id: 1,
    // name: "John Doe",
    age: 25,
    tvStation: "ABC News",
    broadcastPeriodStart: new Date(2021, 6, 15),
    broadcastPeriodEnd: new Date(2021, 6, 20),
    status: "作成完了",
    fileName: "aaaaa.xlsx",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    uploadDate: new Date(),
    message: "あああああ",
    reason: "あああああ",
  },
  {
    id: 2,
    // name: "Jane Smith",
    age: 36,
    tvStation: "BBC",
    broadcastPeriodStart: new Date(2022, 3, 20),
    broadcastPeriodEnd: new Date(2022, 4, 20),
    status: "確定",
    fileName: "bbbbb.xlsx",
    fileUrl: "",
    uploadDate: new Date(),
    message: "ああああああああああああああああああああああああああああああああああああああああ",
    reason: "あああああ",
  },
  {
    id: 3,
    // name: "Bob Johnson",
    age: 28,
    tvStation: "FOX",
    broadcastPeriodStart: new Date(2023, 1, 10),
    broadcastPeriodEnd: new Date(2024, 1, 10),
    status: "差戻し",
    fileName: "ccccc.xlsx",
    fileUrl: "",
    uploadDate: new Date("1995-12-17T03:24"),
    message: "あああああ",
    reason: "ああああああああああああああああああああああああああああああああああああああああ",
  },
];

export const mockTvStations = ["ABC News", "BBC", "ESPN", "NBC", "FOX", "MTV", "Discovery Channel"];
export const mockStatus = ["Status1", "Status2", "Status3", "Status4"];
